# Generated by Django 4.0.1 on 2022-01-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='thumbnail',
            field=models.ImageField(default='default.png', null=True, upload_to=''),
        ),
    ]
